#!/bin/sh

# Usage: cronner-wrap <metric spec> <command>
# Where the arguments are:
#    metric spec: String in the form of namespace.metric:timer_name. For example, you might pass
#                 invoicing.crons:charge_customers. This will have cronner emit DataDog metrics
#                 under "invoicing.crons.time" and "invoicing.crons.exit_code" with a
#                 "timer: charge_customers" tag.
#    command: The actual cron command to run, e.g. newrelic-admin run-python -m mnanage charge_customers

set -e

NAMESPACE=$(echo $1 | cut -d'.' -f1)
METRIC=$(echo $1 | cut -d'.' -f2 | cut -d ':' -f1)
TIMER=$(echo $1 | cut -d':' -f2)

shift
COMMAND=$@

DOCKER_HOST=$(ip route | awk '/default/ { print $3 }')

cronner -p -H $DOCKER_HOST -N $NAMESPACE -l $METRIC -t timer:$TIMER -- $COMMAND
